spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/plantodo
    username: ptd
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: messages, errors

logging.level:
  org.hibernate.SQL: debug


